import os

LLM_CONNECTION_TIMEOUT = int(os.getenv("LLM_CONNECTION_TIMEOUT", "300"))

LLM_CONNECTION_POOL_LIMIT = int(os.getenv("LLM_CONNECTION_POOL_LIMIT", "50"))

LLM_CONNECTION_POOL_LIMIT_PER_HOST =  int(os.getenv("LLM_CONNECTION_POOL_LIMIT_PER_HOST", "50"))